version: '3'

services:
  engine-whatsapp-demo:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - 9000:9000
      - 7000:7000
    extra_hosts:
      - 'localhost:172.17.0.1'
  prometheus:
    image: prom/prometheus:v2.20.1
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana:7.1.5
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    ports:
      - 3000:3000
volumes:
  prometheus_data: {}
