version: '3'

services:
  engine-whatsapp-demo:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    env_file:
      - ../config/.env
    ports:
      - 9000:9000
      - 7000:7000
    extra_hosts:
      - 'localhost:172.17.0.1'
